### ISSUE TITLE
I can't download the data

### ISSUE THREAD

**Issue by ganhao88688** [davidserra9/tracknet#1]
I can't download the data from [AI City Challenge 22](https://www.aicitychallenge.org/2022-data-and-evaluation/).
Also, Datasets Request Form said "Commercial emails such as Gmail and QQmail should not be used.".
I don't have institutional email.

**Comment by davidserra9** [comment]
I'm sorry, but the dataset providers (NVIDIA) are the ones who set the download conditions. You could try contacting aicitychallenges@gmail.com and ask for the dataset.

However, you could use other MTMC datasets such as Duke MTMC or Labeled Pedestrian in the Wild. (You could see [NEU-Gou/awesome-reid-dataset](https://github.com/NEU-Gou/awesome-reid-dataset#deepsportradar-reid))
